version: '3'
services:
  server:
    build: ./server/build/docker
    ports:
     - "8080:8080"
    depends_on:
     - "mongo-db"
    links:
     - "mongo-db"
  mongo-db:
    image: "mongo:latest"
  ui:
    build: ./ui
    ports: 
      - "80:80"